name = "sticky-cart-bar"
type = "theme"
uid = "445cad47-2a36-125a-a4cf-4403947da4f1ba6bf19c"

[extension_points.theme.app_blocks]
icon = "assets/icon.svg"

[[extensions]]
type = "theme_app_extension"
name = "Sticky Add to Cart"
handle = "sticky-cart-bar"
